#yaml
name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'v22.3.0'

    - name: Install dependencies
      run: npm install

    - name: run test
      run: echo "running test"

    - name: Build
      run: npm run build  

    - name: run deployment
      run: echo "this pipeline is running"